// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBalanceLog = "balance_logs"

// BalanceLog mapped from table <balance_logs>
type BalanceLog struct {
	BalanceLogID         int32     `gorm:"column:balance_log_id;primaryKey;autoIncrement:false" json:"balance_log_id"`
	BalanceLogAmount     float64   `gorm:"column:balance_log_amount;not null" json:"balance_log_amount"`
	BalanceLogNotes      *string   `gorm:"column:balance_log_notes" json:"balance_log_notes"`
	BalanceLogAttachment *[]byte   `gorm:"column:balance_log_attachment" json:"balance_log_attachment"`
	BalanceLogTimeAdded  time.Time `gorm:"column:balance_log_time_added;not null" json:"balance_log_time_added"`
}

// TableName BalanceLog's table name
func (*BalanceLog) TableName() string {
	return TableNameBalanceLog
}
