// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBalance = "balances"

// Balance mapped from table <balances>
type Balance struct {
	BalanceID     int32   `gorm:"column:balance_id;primaryKey;autoIncrement:false" json:"balance_id"`
	BalanceAmount float64 `gorm:"column:balance_amount;not null" json:"balance_amount"`
}

// TableName Balance's table name
func (*Balance) TableName() string {
	return TableNameBalance
}
