// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItem = "items"

// Item mapped from table <items>
type Item struct {
	ItemID          int32   `gorm:"column:item_id;primaryKey;autoIncrement:true" json:"item_id"`
	ItemName        string  `gorm:"column:item_name;not null" json:"item_name"`
	ItemDescription *string `gorm:"column:item_description" json:"item_description"`
}

// TableName Item's table name
func (*Item) TableName() string {
	return TableNameItem
}
