// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRecurringBill = "recurring_bills"

// RecurringBill mapped from table <recurring_bills>
type RecurringBill struct {
	ID            int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SupplierID    int32      `gorm:"column:supplier_id;not null" json:"supplier_id"`
	Frequency     string     `gorm:"column:frequency;not null" json:"frequency"`
	Total         float64    `gorm:"column:total;not null" json:"total"`
	Notes         *string    `gorm:"column:notes" json:"notes"`
	ShippingCost  float64    `gorm:"column:shipping_cost;not null" json:"shipping_cost"`
	AccountNumber *string    `gorm:"column:account_number" json:"account_number"`
	BankName      *string    `gorm:"column:bank_name" json:"bank_name"`
	StartDate     time.Time  `gorm:"column:start_date;not null" json:"start_date"`
	EndDate       *time.Time `gorm:"column:end_date" json:"end_date"`
	PaymentDue    int32      `gorm:"column:payment_due;not null" json:"payment_due"`
	Status        string     `gorm:"column:status;not null" json:"status"`
}

// TableName RecurringBill's table name
func (*RecurringBill) TableName() string {
	return TableNameRecurringBill
}
