// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVSupplierInvoice = "v_supplier_invoice"

// VSupplierInvoice mapped from table <v_supplier_invoice>
type VSupplierInvoice struct {
	InvoicesID       int32     `gorm:"column:invoices_id;not null;default:0" json:"invoices_id"`
	SupplierID       int32     `gorm:"column:supplier_id;not null" json:"supplier_id"`
	InvoiceStartDate time.Time `gorm:"column:invoice_start_date;not null" json:"invoice_start_date"`
	InvoiceDueDate   time.Time `gorm:"column:invoice_due_date;not null" json:"invoice_due_date"`
	InvoiceNumber    string    `gorm:"column:invoice_number;not null" json:"invoice_number"`
	InvoiceTitle     *string   `gorm:"column:invoice_title" json:"invoice_title"`
	InvoiceStatus    string    `gorm:"column:invoice_status;not null" json:"invoice_status"`
	SupplierName     string    `gorm:"column:supplier_name;not null" json:"supplier_name"`
	InvoiceTotal     float64   `gorm:"column:invoice_total;not null" json:"invoice_total"`
}

// TableName VSupplierInvoice's table name
func (*VSupplierInvoice) TableName() string {
	return TableNameVSupplierInvoice
}
